#!/usr/bin/env bash
# This script is displays Hours follows by All Munites

i=0
while [ "$i" -le 12 ]
do
    echo "Hour: $i"
    (( i++ ))

    j=1
    while [ "$j" -le 59 ]
    do
	echo "$j"
	(( j++ ))
    done
done
