#!/usr/bin/env bash
# Bash script listens (-l) to port 98 on localhost via Netcat (nc)
# Run: (terminal 0): sudo ./[filename]
# Run: (terminal 1): telnet localhost 98
# See: (terminal 1): Trying 127.0.0.2... ; Connected to localhost.
# What you type in terminal 1 will show at terminal 0

nc -l 98
